import { StationNode } from "./types";
import { SWR_CORRIDOR_STATIONS } from "./infrastructure";

export interface CorridorSectionRecord {
  sectionId: string;
  fromStationCode: string;
  toStationCode: string;
  fromStationName: string;
  toStationName: string;
  lengthKm: number;
  startKm: number;
  endKm: number;
  sanctionedMpsKmph: number;
  hasPsr: boolean;
  psrSpeedKmph?: number;
  psrReason?: string;
  hasTsr: boolean;
  tsrSpeedKmph?: number;
  tsrReason?: string;
  hasLcGate: boolean;
  lcGateId?: string;
  hasLoopLine: boolean;
  commuterSurgeRisk: "LOW" | "MEDIUM" | "HIGH";
  nominalTransitTimeMin: number;
  bufferSlackAllocatedMin: number;
}

/**
 * High-Precision Section-by-Section Track Database for Mysuru - Bengaluru Corridor
 * Covering all 15 inter-station block sections (138.250 km)
 */
export const CORRIDOR_SECTIONS: CorridorSectionRecord[] = [
  {
    sectionId: "SEC-01",
    fromStationCode: "MYS",
    toStationCode: "NHY",
    fromStationName: "Mysuru Junction",
    toStationName: "Naganahalli",
    lengthKm: 8.55,
    startKm: 0.0,
    endKm: 8.55,
    sanctionedMpsKmph: 110,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 6.2,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-02",
    fromStationCode: "NHY",
    toStationCode: "S",
    fromStationName: "Naganahalli",
    toStationName: "Shrirangapatna",
    lengthKm: 6.20,
    startKm: 8.55,
    endKm: 14.75,
    sanctionedMpsKmph: 110,
    hasPsr: true,
    psrSpeedKmph: 95,
    psrReason: "Cauvery River Bridge Approach Curvature",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 4.8,
    bufferSlackAllocatedMin: 0.5,
  },
  {
    sectionId: "SEC-03",
    fromStationCode: "S",
    toStationCode: "PANP",
    fromStationName: "Shrirangapatna",
    toStationName: "Pandavapura",
    lengthKm: 4.95,
    startKm: 14.75,
    endKm: 19.70,
    sanctionedMpsKmph: 110,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 3.8,
    bufferSlackAllocatedMin: 0.5,
  },
  {
    sectionId: "SEC-04",
    fromStationCode: "PANP",
    toStationCode: "BDRL",
    fromStationName: "Pandavapura",
    toStationName: "Byadarahalli",
    lengthKm: 9.15,
    startKm: 19.70,
    endKm: 28.85,
    sanctionedMpsKmph: 120,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: true,
    lcGateId: "LC-18",
    hasLoopLine: false,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 5.5,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-05",
    fromStationCode: "BDRL",
    toStationCode: "CGKR",
    fromStationName: "Byadarahalli",
    toStationName: "Chandragirikopal",
    lengthKm: 6.20,
    startKm: 28.85,
    endKm: 35.05,
    sanctionedMpsKmph: 120,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 3.9,
    bufferSlackAllocatedMin: 0.5,
  },
  {
    sectionId: "SEC-06",
    fromStationCode: "CGKR",
    toStationCode: "MYA",
    fromStationName: "Chandragirikopal",
    toStationName: "Mandya",
    lengthKm: 10.316,
    startKm: 35.05,
    endKm: 45.366,
    sanctionedMpsKmph: 110,
    hasPsr: true,
    psrSpeedKmph: 85,
    psrReason: "Mandya Yard Approach Curves & Level Interlocking",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 7.2,
    bufferSlackAllocatedMin: 1.5,
  },
  {
    sectionId: "SEC-07",
    fromStationCode: "MYA",
    toStationCode: "HNK",
    fromStationName: "Mandya",
    toStationName: "Hanakere",
    lengthKm: 9.784,
    startKm: 45.366,
    endKm: 55.15,
    sanctionedMpsKmph: 130,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 5.8,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-08",
    fromStationCode: "HNK",
    toStationCode: "MAD",
    fromStationName: "Hanakere",
    toStationName: "Maddur",
    lengthKm: 9.39,
    startKm: 55.15,
    endKm: 64.54,
    sanctionedMpsKmph: 120,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 5.6,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-09",
    fromStationCode: "MAD",
    toStationCode: "SET",
    fromStationName: "Maddur",
    toStationName: "Settihally",
    lengthKm: 10.81,
    startKm: 64.54,
    endKm: 75.35,
    sanctionedMpsKmph: 130,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: true,
    lcGateId: "LC-42",
    hasLoopLine: false,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 6.2,
    bufferSlackAllocatedMin: 1.5,
  },
  {
    sectionId: "SEC-10",
    fromStationCode: "SET",
    toStationCode: "CPT",
    fromStationName: "Settihally",
    toStationName: "Channapatna",
    lengthKm: 7.452,
    startKm: 75.35,
    endKm: 82.802,
    sanctionedMpsKmph: 120,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "MEDIUM",
    nominalTransitTimeMin: 4.6,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-11",
    fromStationCode: "CPT",
    toStationCode: "RMGM",
    fromStationName: "Channapatna",
    toStationName: "Ramanagaram",
    lengthKm: 11.058,
    startKm: 82.802,
    endKm: 93.860,
    sanctionedMpsKmph: 120,
    hasPsr: true,
    psrSpeedKmph: 90,
    psrReason: "Ramanagaram Rocky Cuttings & Reverse Curves",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 6.8,
    bufferSlackAllocatedMin: 1.5,
  },
  {
    sectionId: "SEC-12",
    fromStationCode: "RMGM",
    toStationCode: "BID",
    fromStationName: "Ramanagaram",
    toStationName: "Bidadi",
    lengthKm: 14.766,
    startKm: 93.860,
    endKm: 108.626,
    sanctionedMpsKmph: 130,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: true,
    lcGateId: "LC-67",
    hasLoopLine: true,
    commuterSurgeRisk: "MEDIUM",
    nominalTransitTimeMin: 8.2,
    bufferSlackAllocatedMin: 2.5, // Major double track high-speed slack recovery section
  },
  {
    sectionId: "SEC-13",
    fromStationCode: "BID",
    toStationCode: "HJL",
    fromStationName: "Bidadi",
    toStationName: "Hejjala",
    lengthKm: 6.824,
    startKm: 108.626,
    endKm: 115.450,
    sanctionedMpsKmph: 130,
    hasPsr: false,
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "LOW",
    nominalTransitTimeMin: 4.1,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-14",
    fromStationCode: "HJL",
    toStationCode: "KGI",
    fromStationName: "Hejjala",
    toStationName: "Kengeri",
    lengthKm: 10.582,
    startKm: 115.450,
    endKm: 126.032,
    sanctionedMpsKmph: 110,
    hasPsr: true,
    psrSpeedKmph: 75,
    psrReason: "Kengeri Suburban Approach & Turnout Network",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 7.4,
    bufferSlackAllocatedMin: 2.0,
  },
  {
    sectionId: "SEC-15",
    fromStationCode: "KGI",
    toStationCode: "NYH",
    fromStationName: "Kengeri",
    toStationName: "Nayandahalli",
    lengthKm: 4.818,
    startKm: 126.032,
    endKm: 130.850,
    sanctionedMpsKmph: 90,
    hasPsr: true,
    psrSpeedKmph: 70,
    psrReason: "High-density urban viaduct & level crossings",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: false,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 3.8,
    bufferSlackAllocatedMin: 1.0,
  },
  {
    sectionId: "SEC-16",
    fromStationCode: "NYH",
    toStationCode: "SBC",
    fromStationName: "Nayandahalli",
    toStationName: "KSR Bengaluru City",
    lengthKm: 7.400,
    startKm: 130.850,
    endKm: 138.250,
    sanctionedMpsKmph: 60,
    hasPsr: true,
    psrSpeedKmph: 30,
    psrReason: "SBC Terminal Throat Interlocking, Outer Home Signal & Diamond Crossings",
    hasTsr: false,
    hasLcGate: false,
    hasLoopLine: true,
    commuterSurgeRisk: "HIGH",
    nominalTransitTimeMin: 9.5,
    bufferSlackAllocatedMin: 4.0, // Terminal buffer allowance
  },
];
