import { StationNode, SpeedRestrictionRecord, LevelCrossingGate } from "./types";

/**
 * Official South Western Railway (SWR) Chainage:
 * SBC = km 0.000, MYS = km 138.250 (Total Corridor Length = 138.250 km)
 * Includes all major stations and intermediate halts.
 */
export const SWR_CORRIDOR_STATIONS: StationNode[] = [
  {
    code: "MYS",
    name: "Mysuru Junction",
    chainageFromSbcKm: 138.250,
    distanceFromMysKm: 0.000,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 6,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "NHY",
    name: "Naganahalli",
    chainageFromSbcKm: 129.700,
    distanceFromMysKm: 8.550,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "S",
    name: "Shrirangapatna",
    chainageFromSbcKm: 123.500,
    distanceFromMysKm: 14.750,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "PANP",
    name: "Pandavapura",
    chainageFromSbcKm: 118.550,
    distanceFromMysKm: 19.700,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "BDRL",
    name: "Byadarahalli",
    chainageFromSbcKm: 109.400,
    distanceFromMysKm: 28.850,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: false,
    loopSpeedKmph: 15,
  },
  {
    code: "CGKR",
    name: "Chandragirikopal",
    chainageFromSbcKm: 103.200,
    distanceFromMysKm: 35.050,
    isMajorJunction: false,
    hasPassengerHalts: false,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "MYA",
    name: "Mandya",
    chainageFromSbcKm: 92.884,
    distanceFromMysKm: 45.366,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 3,
    hasLoopLine: true,
    loopSpeedKmph: 30,
    commuterSurgeProne: true,
  },
  {
    code: "HNK",
    name: "Hanakere",
    chainageFromSbcKm: 83.100,
    distanceFromMysKm: 55.150,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "MAD",
    name: "Maddur",
    chainageFromSbcKm: 73.710,
    distanceFromMysKm: 64.540,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 3,
    hasLoopLine: true,
    loopSpeedKmph: 30,
    commuterSurgeProne: true,
  },
  {
    code: "SET",
    name: "Settihally",
    chainageFromSbcKm: 62.900,
    distanceFromMysKm: 75.350,
    isMajorJunction: false,
    hasPassengerHalts: false,
    platformCount: 2,
    hasLoopLine: false,
    loopSpeedKmph: 15,
  },
  {
    code: "CPT",
    name: "Channapatna",
    chainageFromSbcKm: 55.448,
    distanceFromMysKm: 82.802,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 3,
    hasLoopLine: true,
    loopSpeedKmph: 30,
    commuterSurgeProne: true,
  },
  {
    code: "RMGM",
    name: "Ramanagaram",
    chainageFromSbcKm: 44.390,
    distanceFromMysKm: 93.860,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 3,
    hasLoopLine: true,
    loopSpeedKmph: 30,
    commuterSurgeProne: true,
  },
  {
    code: "BID",
    name: "Bidadi",
    chainageFromSbcKm: 29.624,
    distanceFromMysKm: 108.626,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 3,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "HJL",
    name: "Hejjala",
    chainageFromSbcKm: 22.800,
    distanceFromMysKm: 115.450,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: true,
    loopSpeedKmph: 30,
  },
  {
    code: "KGI",
    name: "Kengeri",
    chainageFromSbcKm: 12.218,
    distanceFromMysKm: 126.032,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 4,
    hasLoopLine: true,
    loopSpeedKmph: 30,
    commuterSurgeProne: true,
  },
  {
    code: "NYH",
    name: "Nayandahalli",
    chainageFromSbcKm: 7.400,
    distanceFromMysKm: 130.850,
    isMajorJunction: false,
    hasPassengerHalts: true,
    platformCount: 2,
    hasLoopLine: false,
    loopSpeedKmph: 15,
  },
  {
    code: "SBC",
    name: "KSR Bengaluru City",
    chainageFromSbcKm: 0.000,
    distanceFromMysKm: 138.250,
    isMajorJunction: true,
    hasPassengerHalts: true,
    platformCount: 10,
    hasLoopLine: true,
    loopSpeedKmph: 15,
  },
];

/**
 * Permanent Speed Restrictions (PSR) & Curves along the corridor
 */
export const DEFAULT_PSR_LIST: SpeedRestrictionRecord[] = [
  {
    id: "PSR-01",
    type: "PSR",
    fromChainageKm: 91.5, // Around Ramanagaram curves
    toChainageKm: 95.0,
    speedLimitKmph: 90,
    direction: "BOTH",
    cause: "Curvature & Gradient Transition (Ramanagaram section)",
    authority: "SWR Eng Circular 2023/14",
    active: true,
  },
  {
    id: "PSR-02",
    type: "PSR",
    fromChainageKm: 125.0, // KGI to NYH approach
    toChainageKm: 132.0,
    speedLimitKmph: 75,
    direction: "BOTH",
    cause: "Suburban high-density zone & turnout approach",
    authority: "SWR Operating Order 88",
    active: true,
  },
  {
    id: "PSR-03",
    type: "PSR",
    fromChainageKm: 134.5, // SBC Yard Throat
    toChainageKm: 138.25,
    speedLimitKmph: 30,
    direction: "BOTH",
    cause: "SBC Station Interlocked Yard Complex & Cross-overs",
    authority: "Station Working Rules (SWR-SBC)",
    active: true,
  },
];

/**
 * Level Crossing Gates along the corridor
 */
export const DEFAULT_LC_GATES: LevelCrossingGate[] = [
  {
    id: "LC-18",
    chainageKm: 34.2, // Near Mandya approach
    section: "PANP - MYA",
    isInterlocked: true,
    normalRoadClosureSec: 90,
    status: "LOCKED_CLOSED",
    signalDetentionMin: 0,
  },
  {
    id: "LC-42",
    chainageKm: 88.5, // Near Channapatna
    section: "MAD - CPT",
    isInterlocked: true,
    normalRoadClosureSec: 120,
    status: "LOCKED_CLOSED",
    signalDetentionMin: 0,
  },
  {
    id: "LC-67",
    chainageKm: 112.0, // Bidadi industrial feeder
    section: "BID - HJL",
    isInterlocked: true,
    normalRoadClosureSec: 150,
    status: "LOCKED_CLOSED",
    signalDetentionMin: 0,
  },
];
