import { TrainConfig } from "./types";

/**
 * Authentic Official Indian Railways (SWR / NTES / IRCTC) Master Daily Train Catalog
 * Corridor: Mysuru Junction (MYS) ➔ KSR Bengaluru City (SBC) [138.25 km]
 */
export const CORRIDOR_ACTIVE_TRAINS: TrainConfig[] = [
  {
    id: "16586",
    name: "MRDW - SMVB Express (Early Morning)",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "03:45",
    scheduledArr: "06:25",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WDP-4D #40182",
    coaches: 18,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
    scheduledStops: ["MYS", "PANP", "MYA", "MAD", "RMGM", "BID", "KGI", "SBC"],
    dwellMinutes: {
      MYS: 0,
      PANP: 1,
      MYA: 2,
      MAD: 1,
      RMGM: 1,
      BID: 1,
      KGI: 2,
      SBC: 0,
    },
  },
  {
    id: "16215",
    name: "Chamundi Express (Morning Commuter)",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "06:45",
    scheduledArr: "09:35",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30482 (RTIS-NavIC)",
    coaches: 21,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 4,
    scheduledStops: [
      "MYS",
      "PANP",
      "MYA",
      "MAD",
      "CPT",
      "RMGM",
      "BID",
      "KGI",
      "NYH",
      "SBC",
    ],
    dwellMinutes: {
      MYS: 0,
      PANP: 1,
      MYA: 2,
      MAD: 2,
      CPT: 1,
      RMGM: 2,
      BID: 1,
      KGI: 2,
      NYH: 1,
      SBC: 0,
    },
  },
  {
    id: "12613",
    name: "Wodeyar Superfast Express (Midday)",
    type: "SUPERFAST",
    priorityTier: 2,
    scheduledDep: "11:30",
    scheduledArr: "14:00",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30510 (LHB Rake)",
    coaches: 22,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.65,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 2,
    scheduledStops: ["MYS", "MYA", "RMGM", "KGI", "SBC"],
    dwellMinutes: {
      MYS: 0,
      MYA: 1,
      RMGM: 1,
      KGI: 1,
      SBC: 0,
    },
  },
  {
    id: "20608",
    name: "Vande Bharat Express (MYS-MAS)",
    type: "VANDE_BHARAT",
    priorityTier: 1,
    scheduledDep: "13:05",
    scheduledArr: "14:45",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "Trainset EMU #20608 (Distributed Traction)",
    coaches: 8,
    sectionalMpsKmph: 130,
    nominalDecelerationMps2: 0.90,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
    scheduledStops: ["MYS", "SBC"],
    dwellMinutes: {
      MYS: 0,
      SBC: 0,
    },
  },
  {
    id: "66552",
    name: "Mysuru - SBC MEMU Commuter",
    type: "MEMU",
    priorityTier: 3,
    scheduledDep: "13:45",
    scheduledArr: "17:20",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "3-Phase MEMU #1104",
    coaches: 12,
    sectionalMpsKmph: 95,
    nominalDecelerationMps2: 0.70,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
    scheduledStops: [
      "MYS",
      "NHY",
      "S",
      "PANP",
      "BDRL",
      "CGKR",
      "MYA",
      "HNK",
      "MAD",
      "SET",
      "CPT",
      "RMGM",
      "BID",
      "HJL",
      "KGI",
      "NYH",
      "SBC",
    ],
    dwellMinutes: {
      MYS: 0,
      NHY: 1,
      S: 1,
      PANP: 1,
      BDRL: 1,
      CGKR: 1,
      MYA: 2,
      HNK: 1,
      MAD: 2,
      SET: 1,
      CPT: 1,
      RMGM: 2,
      BID: 1,
      HJL: 1,
      KGI: 2,
      NYH: 1,
      SBC: 0,
    },
  },
  {
    id: "12008",
    name: "Shatabdi Express (MYS-MAS)",
    type: "SHATABDI",
    priorityTier: 1,
    scheduledDep: "14:15",
    scheduledArr: "16:05",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #37012 (LHB Rake)",
    coaches: 14,
    sectionalMpsKmph: 120,
    nominalDecelerationMps2: 0.75,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
    scheduledStops: ["MYS", "SBC"],
    dwellMinutes: {
      MYS: 0,
      SBC: 0,
    },
  },
  {
    id: "16232",
    name: "Mayiladuturai Express (Evening)",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "16:15",
    scheduledArr: "18:50",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30412 (LHB Rake)",
    coaches: 22,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 2,
    scheduledStops: ["MYS", "MYA", "MAD", "KGI", "SBC"],
    dwellMinutes: {
      MYS: 0,
      MYA: 2,
      MAD: 2,
      KGI: 2,
      SBC: 0,
    },
  },
  {
    id: "16236",
    name: "Tuticorin Express (Evening)",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "18:20",
    scheduledArr: "20:50",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30355 (LHB Rake)",
    coaches: 21,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 2,
    scheduledStops: ["MYS", "PANP", "MYA", "MAD", "CPT", "RMGM", "BID", "KGI", "SBC"],
    dwellMinutes: {
      MYS: 0,
      PANP: 1,
      MYA: 2,
      MAD: 2,
      CPT: 1,
      RMGM: 2,
      BID: 1,
      KGI: 2,
      SBC: 0,
    },
  },
  {
    id: "16022",
    name: "Kaveri Express (Night)",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "21:00",
    scheduledArr: "23:45",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30490 (LHB Rake)",
    coaches: 22,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 3,
    scheduledStops: ["MYS", "PANP", "MYA", "MAD", "CPT", "RMGM", "BID", "KGI", "SBC"],
    dwellMinutes: {
      MYS: 0,
      PANP: 1,
      MYA: 2,
      MAD: 2,
      CPT: 1,
      RMGM: 2,
      BID: 1,
      KGI: 2,
      SBC: 0,
    },
  },
  {
    id: "BOXN-58219",
    name: "Automobile Cargo Goods Rake (Night Freight)",
    type: "FREIGHT_BOXN",
    priorityTier: 4,
    scheduledDep: "01:00",
    scheduledArr: "04:30",
    origin: "MYS Goods Yard",
    destination: "Whitefield Goods Terminal",
    locoType: "Twin WAG-9HC #31890",
    coaches: 45,
    sectionalMpsKmph: 75,
    nominalDecelerationMps2: 0.30,
    currentLocationKm: 0.0,
    currentSpeedKmph: 0.0,
    initialDelayMin: 12,
    scheduledStops: ["MYS", "SBC"],
    dwellMinutes: {
      MYS: 0,
      SBC: 0,
    },
  },
];
