import { TrainConfig } from "./types";

export const CORRIDOR_ACTIVE_TRAINS: TrainConfig[] = [
  {
    id: "20608",
    name: "Vande Bharat Express",
    type: "VANDE_BHARAT",
    priorityTier: 1,
    scheduledDep: "13:05",
    scheduledArr: "14:50",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "Trainset #20608 (Distributed Traction)",
    coaches: 8,
    sectionalMpsKmph: 130,
    nominalDecelerationMps2: 0.90,
    currentLocationKm: 126.032, // Approaching Kengeri (KGI)
    currentSpeedKmph: 92.0,
    initialDelayMin: 2,
  },
  {
    id: "16215",
    name: "Chamundi Express",
    type: "EXPRESS",
    priorityTier: 2,
    scheduledDep: "06:45",
    scheduledArr: "09:25",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30482 (RTIS-NavIC)",
    coaches: 21,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.60,
    currentLocationKm: 138.250, // Arrived at SBC
    currentSpeedKmph: 0.0,
    initialDelayMin: 7,
  },
  {
    id: "12008",
    name: "Shatabdi Express",
    type: "SHATABDI",
    priorityTier: 1,
    scheduledDep: "14:15",
    scheduledArr: "16:15",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #37012 (LHB Rake)",
    coaches: 14,
    sectionalMpsKmph: 120,
    nominalDecelerationMps2: 0.75,
    currentLocationKm: 0.000, // Boarding MYS
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
  },
  {
    id: "12614",
    name: "Wodeyar Superfast Exp",
    type: "SUPERFAST",
    priorityTier: 2,
    scheduledDep: "15:15",
    scheduledArr: "17:45",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "WAP-7 #30510",
    coaches: 22,
    sectionalMpsKmph: 110,
    nominalDecelerationMps2: 0.65,
    currentLocationKm: 0.000,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
  },
  {
    id: "06560",
    name: "MYS-SBC MEMU Commuter",
    type: "MEMU",
    priorityTier: 3,
    scheduledDep: "15:30",
    scheduledArr: "18:45",
    origin: "MYS (Mysuru Jn)",
    destination: "SBC (KSR Bengaluru)",
    locoType: "3-Phase MEMU #1104",
    coaches: 12,
    sectionalMpsKmph: 95,
    nominalDecelerationMps2: 0.70,
    currentLocationKm: 0.000,
    currentSpeedKmph: 0.0,
    initialDelayMin: 0,
  },
  {
    id: "BOXN-58219",
    name: "Automobile Cargo Goods",
    type: "FREIGHT_BOXN",
    priorityTier: 4,
    scheduledDep: "12:30",
    scheduledArr: "16:00",
    origin: "MYS Yard",
    destination: "Whitefield Goods Terminal",
    locoType: "Twin WAG-9HC #31890",
    coaches: 45,
    sectionalMpsKmph: 75,
    nominalDecelerationMps2: 0.30,
    currentLocationKm: 108.626, // Stabled at Bidadi Loop 3
    currentSpeedKmph: 0.0,
    initialDelayMin: 18,
  },
];
