/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DatasetRouteImport } from './routes/dataset'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ModelRouteImport } from './routes/model'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SlidesRouteImport } from './routes/slides'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DatasetRoute = DatasetRouteImport.update({
  id: '/dataset',
  path: '/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/demo': typeof DemoRoute
  '/model': typeof ModelRoute
  '/simulation': typeof SimulationRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/demo': typeof DemoRoute
  '/model': typeof ModelRoute
  '/simulation': typeof SimulationRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dataset': typeof DatasetRoute
  '/demo': typeof DemoRoute
  '/model': typeof ModelRoute
  '/simulation': typeof SimulationRoute
  '/slides': typeof SlidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dataset' | '/demo' | '/model' | '/simulation' | '/slides'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dataset' | '/demo' | '/model' | '/simulation' | '/slides'
  id:
    | '__root__'
    | '/'
    | '/dataset'
    | '/demo'
    | '/model'
    | '/simulation'
    | '/slides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasetRoute: typeof DatasetRoute
  DemoRoute: typeof DemoRoute
  ModelRoute: typeof ModelRoute
  SimulationRoute: typeof SimulationRoute
  SlidesRoute: typeof SlidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dataset': {
      id: '/dataset'
      path: '/dataset'
      fullPath: '/dataset'
      preLoaderRoute: typeof DatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasetRoute: DatasetRoute,
  DemoRoute: DemoRoute,
  ModelRoute: ModelRoute,
  SimulationRoute: SimulationRoute,
  SlidesRoute: SlidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
